(global-set-key (kbd "C-x o") 'switch-window)
(global-set-key (kbd "C-x a") 'ace-jump-mode)
(global-set-key (kbd "C-x r t") 'inline-string-rectangle)
(global-set-key (kbd "C-@") 'set-mark-command)
(global-set-key (kbd "M-SPC") 'er/expand-region)
(global-set-key (kbd "C-x SPC") 'set-rectangular-region-anchor)
(global-set-key (kbd "C-x /") 'mc/mark-all-like-this)
(global-set-key (kbd "C-x .") 'mc/mark-next-like-this)
(global-set-key (kbd "C-p") 'fill-paragraph)
